# this helped to hide the secret settings from git
# but at the same time not set them in the envirnment variables of the shell.
# config/s3.yml

development: &DEFAULTS
  bucket: gl-music-site
  access_key_id: 'AKIAITIPG6T7WY4DD7IQ'
  secret_access_key: '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'

test:
  <<: *DEFAULTS
  bucket: gl-music-site

production:
  <<: *DEFAULTS
  bucket: gl-music-site

staging:
  <<: *DEFAULTS
bucket: gl-music-site
